version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestNewFeatureDProject
  gitServerName: SanthoshKUserSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.testnewfeatured.integrations:NewFlow2208
  packages:
  - name: TestNewFeatureDProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
